SCP 939 PlayingFootstep Reimplementation
Exiled-Official/EXILED pull request #102
Opened 2024-07-19 10:15 UTC by XKaguya

Reimplementation from previous rep

2024-07-19 10:20 UTC, Vladislav-CS submitted a review, later dismissed

2024-07-20 12:29 UTC, Jesus-QC approved these changes

2024-07-20 12:59 UTC, IRacle1 requested changes
other seems ok

2024-07-20 12:59 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
> +            newInstructions.InsertRange(index, new CodeInstruction[]
as i saw, transpiler could be rewritten to a a more simply code, like inserting code after `if` brackets using `MoveLabelsFrom` method

2024-07-20 12:59 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
> +            newInstructions.InsertRange(index, new CodeInstruction[]
you could remove `base.CheckVisibility(model.OwnerHub)` instructions and `cnt` label in that case

2024-07-20 12:59 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
> +            newInstructions.InsertRange(index, new CodeInstruction[]
<img width="647" alt="image" src="https://github.com/user-attachments/assets/dd7195a9-e1a4-482f-a97e-c6f7caaa3cf7">

2024-07-20 12:59 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
> +                yield return instruction;
we have pattern for that😈
```suggestion
            for (int z = 0; z < newInstructions.Count; z++)
                yield return newInstructions[z];
```

2024-07-20 13:41 UTC, XKaguya commented on EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
> +                yield return instruction;
> we have pattern for that😈

sry but why for since the IDE suggest me to change into for loop, just dont understand, just for beauity and format ?

2024-07-20 13:41 UTC, XKaguya commented on EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
> +            newInstructions.InsertRange(index, new CodeInstruction[]
> you could remove `base.CheckVisibility(model.OwnerHub)` instructions and `cnt` label in that case

I'll do that later, Thank you

2024-07-20 14:06 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
> +                yield return instruction;
more like code consistency, we use that `for` instead `foreach` in all transpilers 

theres no actual difference in performance/readability, just a common practice in our transpilers

2024-07-20 15:13 UTC, Jesus-QC requested changes

2024-07-20 15:13 UTC, Jesus-QC commented on EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
> +    [HarmonyPatch(typeof(FootstepRippleTrigger), nameof(FootstepRippleTrigger.OnFootstepPlayed))]
Add the Event attribute

2024-07-20 16:21 UTC, XKaguya commented
I think its done. Patch successed locally. But cannot test since i have only one pc. This patch was tested before

2024-07-20 16:28 UTC, IRacle1 commented
ok ill check it

2024-07-20 16:29 UTC, Jesus-QC commented
@XKaguya change the target branch to dev

2024-07-20 16:30 UTC, closed without merging