`ChangingRadioPresetEventArgs::Radio` peoperty
Exiled-Official/EXILED pull request #109
Opened 2024-07-19 14:09 UTC by IRacle1

just pr my funy thing i added in exiled before dildo drama

2024-07-19 14:38 UTC, Jesus-QC approved these changes

2024-07-19 17:55 UTC, louis1706 approved these changes

2024-07-19 18:11 UTC, Vladislav-CS requested changes

2024-07-19 18:11 UTC, Vladislav-CS commented on EXILED/Exiled.Events/EventArgs/Player/ChangingRadioPresetEventArgs.cs
> +        public Item Item => Radio;
Add an `obsolete` attribute

2024-07-19 18:20 UTC, IRacle1 commented on EXILED/Exiled.Events/EventArgs/Player/ChangingRadioPresetEventArgs.cs
> +        public Item Item => Radio;
Why? It is for implementing `IItemEvent`, and i dont see why it logically should be obsolete

2024-07-19 19:29 UTC, louis1706 commented on EXILED/Exiled.Events/EventArgs/Player/ChangingRadioPresetEventArgs.cs
> +        public Item Item => Radio;
i thinks vlad didn't get why this exist lol

2024-07-19 19:34 UTC, Vladislav-CS commented on EXILED/Exiled.Events/EventArgs/Player/ChangingRadioPresetEventArgs.cs
> +        public Item Item => Radio;
Ah, you added it, anyway, there is no need to add it as Radio contains all properties of Item class

2024-07-19 21:57 UTC, Misfiy commented on EXILED/Exiled.Events/EventArgs/Player/ChangingRadioPresetEventArgs.cs
> +        public Item Item => Radio;
Is needed for IItemEvent

2024-07-19 22:02 UTC, IRacle1 commented on EXILED/Exiled.Events/EventArgs/Player/ChangingRadioPresetEventArgs.cs
> +        public Item Item => Radio;
- It cant be implemented other way
- i see no problem in that
- 🥱🥱
- its cool
- close review

2024-07-20 09:59 UTC, Vladislav-CS approved these changes

2024-07-20 14:03 UTC, merged