`ShouldScp079RecontainedWhenNoScps` feature
Exiled-Official/EXILED pull request #134
Opened 2024-07-22 12:20 UTC by IRacle1

Exiled.Events config for disabling scp079 auto recontamination when no scps left😎

2024-07-22 18:52 UTC, louis1706 requested changes

2024-07-22 18:52 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Generic/Scp079Recontain.cs
> +                    new(OpCodes.Brfalse_S, ret),
shouldn't we add an event too ?

2024-07-23 10:52 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Generic/Scp079Recontain.cs
> +                    new(OpCodes.Brfalse_S, ret),
We already have `Recontained` event for 079

2024-07-26 11:05 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Generic/Scp079Recontain.cs
> +                    new(OpCodes.Brfalse_S, ret),
> We already have `Recontained` event for 079

you can't differentiate it from ScpRecontain or Recontain because his glass trigger has been broken

2024-12-27 20:29 UTC, closed without merging