Hurting and Hurt events firing fix
Exiled-Official/EXILED pull request #75
Opened 2024-07-18 13:56 UTC by Vladislav-CS

The thing is when you either fall in void or get killed by nuke, you receive -1 damage which means death. Hurting and Hurt events fire and if plugin somehow reduces the damage (it becomes not -1), a player doesn't die. This PR fixes it

2024-07-18 19:47 UTC, louis1706 commented
I fully disagree with this change that isn't a fix but breaking of many feature

2024-07-18 20:06 UTC, louis1706 requested changes
My Opinion it's than this is not a bug but a features if plugin got issue with it 

It's plugin ISSUE

2024-07-19 11:44 UTC, louis1706 approved these changes

2024-07-20 11:51 UTC, Jesus-QC approved these changes

2024-07-20 13:12 UTC, IRacle1 approved these changes

2024-07-20 14:09 UTC, merged